# Generated by Django 6.0.7 on 2026-07-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.sourceticket'),
        ),
    ]
