# Generated by Django 6.0.7 on 2026-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_sourceticket_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
